name = "apps-sheikhhussien"
type = "javascript"
account_id = "26fd3146d5d95747d6208c34462be1d2"
workers_dev = true

route = "apps.sheikhhussien.com/*"
zone_id = "9117be5e49edd8bcf01aa6ac2e1029f9"

[env.production]
name = "apps-sheikhhussien-prod"
route = "apps.sheikhhussien.com/*"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx"]

[build.upload]
format = "modules"
main = "./dist/index.js"
